from __future__ import annotations

from dataclasses import dataclass
from typing import Any


OPERATIONAL_STATUS_MODEL_ONLY = "MODEL_ONLY"
OPERATIONAL_STATUS_LOCALHOST_FIXTURE_TESTED = "LOCALHOST_FIXTURE_TESTED"
OPERATIONAL_STATUS_SITE_ADAPTER_IMPLEMENTED = "SITE_ADAPTER_IMPLEMENTED"
OPERATIONAL_STATUS_LIVE_SITE_MANUALLY_VERIFIED = "LIVE_SITE_MANUALLY_VERIFIED"

OPERATIONAL_STATUS_LABELS = (
    OPERATIONAL_STATUS_MODEL_ONLY,
    OPERATIONAL_STATUS_LOCALHOST_FIXTURE_TESTED,
    OPERATIONAL_STATUS_SITE_ADAPTER_IMPLEMENTED,
    OPERATIONAL_STATUS_LIVE_SITE_MANUALLY_VERIFIED,
)

CAPTURE_STATUS_SUCCESS = "SUCCESS"
CAPTURE_STATUS_PARTIAL = "PARTIAL"
CAPTURE_STATUS_FAILED = "FAILED"
CAPTURE_STATUS_CANCELLED = "CANCELLED"
CAPTURE_STATUS_NOT_REQUESTED = "NOT_REQUESTED"
CAPTURE_STATUS_UNSUPPORTED = "UNSUPPORTED"
CAPTURE_STATUS_LOGIN_REQUIRED = "LOGIN_REQUIRED"
CAPTURE_STATUS_PAYWALL_VISIBLE = "PAYWALL_VISIBLE"
CAPTURE_STATUS_CHALLENGE_REQUIRES_USER = "CHALLENGE_REQUIRES_USER"
CAPTURE_STATUS_RATE_LIMITED = "RATE_LIMITED"
CAPTURE_STATUS_FORMAT_CHANGED = "FORMAT_CHANGED"
CAPTURE_STATUS_NETWORK_ERROR = "NETWORK_ERROR"
CAPTURE_STATUS_BROWSER_MISSING = "BROWSER_MISSING"
CAPTURE_STATUS_DEPENDENCY_MISSING = "DEPENDENCY_MISSING"

CAPTURE_STATUS_CODES = (
    CAPTURE_STATUS_SUCCESS,
    CAPTURE_STATUS_PARTIAL,
    CAPTURE_STATUS_FAILED,
    CAPTURE_STATUS_CANCELLED,
    CAPTURE_STATUS_NOT_REQUESTED,
    CAPTURE_STATUS_UNSUPPORTED,
    CAPTURE_STATUS_LOGIN_REQUIRED,
    CAPTURE_STATUS_PAYWALL_VISIBLE,
    CAPTURE_STATUS_CHALLENGE_REQUIRES_USER,
    CAPTURE_STATUS_RATE_LIMITED,
    CAPTURE_STATUS_FORMAT_CHANGED,
    CAPTURE_STATUS_NETWORK_ERROR,
    CAPTURE_STATUS_BROWSER_MISSING,
    CAPTURE_STATUS_DEPENDENCY_MISSING,
)

COMPLETENESS_COMPLETE = "COMPLETE"
COMPLETENESS_PARTIAL_LIMIT_REACHED = "PARTIAL_LIMIT_REACHED"
COMPLETENESS_PARTIAL_VIRTUALIZED = "PARTIAL_VIRTUALIZED"
COMPLETENESS_PARTIAL_LOGIN_REQUIRED = "PARTIAL_LOGIN_REQUIRED"
COMPLETENESS_PARTIAL_CHALLENGE = "PARTIAL_CHALLENGE"
COMPLETENESS_PARTIAL_LOAD_ERROR = "PARTIAL_LOAD_ERROR"
COMPLETENESS_PARTIAL_UNKNOWN = "PARTIAL_UNKNOWN"
COMPLETENESS_NOT_APPLICABLE = "NOT_APPLICABLE"

COMPLETENESS_CODES = (
    COMPLETENESS_COMPLETE,
    COMPLETENESS_PARTIAL_LIMIT_REACHED,
    COMPLETENESS_PARTIAL_VIRTUALIZED,
    COMPLETENESS_PARTIAL_LOGIN_REQUIRED,
    COMPLETENESS_PARTIAL_CHALLENGE,
    COMPLETENESS_PARTIAL_LOAD_ERROR,
    COMPLETENESS_PARTIAL_UNKNOWN,
    COMPLETENESS_NOT_APPLICABLE,
)

FIDELITY_FAITHFUL = "FAITHFUL"
FIDELITY_DERIVED = "DERIVED"
FIDELITY_RAW = "RAW"
FIDELITY_STRUCTURED_EXTRACTION = "STRUCTURED_EXTRACTION"

FIDELITY_CODES = (
    FIDELITY_FAITHFUL,
    FIDELITY_DERIVED,
    FIDELITY_RAW,
    FIDELITY_STRUCTURED_EXTRACTION,
)

DRM_NONE_DETECTED = "NONE_DETECTED"
DRM_SUSPECTED = "SUSPECTED"
DRM_CONFIRMED = "CONFIRMED"
DRM_UNKNOWN = "UNKNOWN"
DRM_RENDERED_OUTPUT_CAPTURE_ALLOWED_BY_PLATFORM = "RENDERED_OUTPUT_CAPTURE_ALLOWED_BY_PLATFORM"
DRM_RENDERED_OUTPUT_CAPTURE_BLOCKED_BY_PLATFORM = "RENDERED_OUTPUT_CAPTURE_BLOCKED_BY_PLATFORM"

DRM_CODES = (
    DRM_NONE_DETECTED,
    DRM_SUSPECTED,
    DRM_CONFIRMED,
    DRM_UNKNOWN,
    DRM_RENDERED_OUTPUT_CAPTURE_ALLOWED_BY_PLATFORM,
    DRM_RENDERED_OUTPUT_CAPTURE_BLOCKED_BY_PLATFORM,
)

ARCHIVE_STATUS_FOUND = "FOUND"
ARCHIVE_STATUS_NOT_FOUND_CONFIRMED = "NOT_FOUND_CONFIRMED"
ARCHIVE_STATUS_MULTIPLE_FOUND = "MULTIPLE_FOUND"
ARCHIVE_STATUS_SUBMISSION_STARTED = "SUBMISSION_STARTED"
ARCHIVE_STATUS_SUBMISSION_COMPLETED = "SUBMISSION_COMPLETED"
ARCHIVE_STATUS_WIP = "WIP"
ARCHIVE_STATUS_CHALLENGE_REQUIRES_USER = "CHALLENGE_REQUIRES_USER"
ARCHIVE_STATUS_FORMAT_CHANGED = "FORMAT_CHANGED"
ARCHIVE_STATUS_SERVICE_UNAVAILABLE = "SERVICE_UNAVAILABLE"
ARCHIVE_STATUS_DNS_FAILURE = "DNS_FAILURE"
ARCHIVE_STATUS_NETWORK_ERROR = "NETWORK_ERROR"
ARCHIVE_STATUS_RATE_LIMITED = "RATE_LIMITED"
ARCHIVE_STATUS_UNKNOWN = "UNKNOWN"

ARCHIVE_STATUS_CODES = (
    ARCHIVE_STATUS_FOUND,
    ARCHIVE_STATUS_NOT_FOUND_CONFIRMED,
    ARCHIVE_STATUS_MULTIPLE_FOUND,
    ARCHIVE_STATUS_SUBMISSION_STARTED,
    ARCHIVE_STATUS_SUBMISSION_COMPLETED,
    ARCHIVE_STATUS_WIP,
    ARCHIVE_STATUS_CHALLENGE_REQUIRES_USER,
    ARCHIVE_STATUS_FORMAT_CHANGED,
    ARCHIVE_STATUS_SERVICE_UNAVAILABLE,
    ARCHIVE_STATUS_DNS_FAILURE,
    ARCHIVE_STATUS_NETWORK_ERROR,
    ARCHIVE_STATUS_RATE_LIMITED,
    ARCHIVE_STATUS_UNKNOWN,
)


@dataclass(frozen=True)
class CaptureStatusCatalog:
    operational_statuses: tuple[str, ...] = OPERATIONAL_STATUS_LABELS
    capture_statuses: tuple[str, ...] = CAPTURE_STATUS_CODES
    completeness_statuses: tuple[str, ...] = COMPLETENESS_CODES
    fidelity_statuses: tuple[str, ...] = FIDELITY_CODES
    drm_statuses: tuple[str, ...] = DRM_CODES
    archive_statuses: tuple[str, ...] = ARCHIVE_STATUS_CODES

    def to_dict(self) -> dict[str, Any]:
        return {
            "archive_statuses": list(self.archive_statuses),
            "capture_statuses": list(self.capture_statuses),
            "completeness_statuses": list(self.completeness_statuses),
            "drm_statuses": list(self.drm_statuses),
            "fidelity_statuses": list(self.fidelity_statuses),
            "operational_statuses": list(self.operational_statuses),
        }


def capture_status_catalog_to_dict() -> dict[str, Any]:
    return CaptureStatusCatalog().to_dict()


def is_known_capture_status(status: str) -> bool:
    return str(status or "").strip().upper() in CAPTURE_STATUS_CODES


def is_known_completeness_status(status: str) -> bool:
    return str(status or "").strip().upper() in COMPLETENESS_CODES


def is_known_fidelity_status(status: str) -> bool:
    return str(status or "").strip().upper() in FIDELITY_CODES
