from __future__ import annotations

from dataclasses import asdict, dataclass
from pathlib import Path
from typing import Any, Iterable, Sequence


EXTERNAL_REFERENCE_ABSORPTION_SCHEMA_VERSION = "external-reference-absorption-v77d"


@dataclass(frozen=True)
class ExternalReferenceAbsorptionEntry:
    reference_name: str
    reference_group: str
    detected_files_or_modules: tuple[str, ...]
    capability_area: str
    useful_logic_to_absorb: tuple[str, ...]
    existing_ytce_equivalent: tuple[str, ...]
    missing_gap: tuple[str, ...]
    safe_absorption_boundary: str
    prohibited_behaviours: tuple[str, ...]
    candidate_patch_id: str
    priority: str
    implementation_status: str

    def to_dict(self) -> dict[str, Any]:
        return asdict(self)


def _entry(
    reference_name: str,
    reference_group: str,
    detected_files_or_modules: Sequence[str],
    capability_area: str,
    useful_logic_to_absorb: Sequence[str],
    existing_ytce_equivalent: Sequence[str],
    missing_gap: Sequence[str],
    safe_absorption_boundary: str,
    prohibited_behaviours: Sequence[str],
    candidate_patch_id: str,
    priority: str,
    implementation_status: str,
) -> ExternalReferenceAbsorptionEntry:
    return ExternalReferenceAbsorptionEntry(
        reference_name=reference_name,
        reference_group=reference_group,
        detected_files_or_modules=tuple(detected_files_or_modules),
        capability_area=capability_area,
        useful_logic_to_absorb=tuple(useful_logic_to_absorb),
        existing_ytce_equivalent=tuple(existing_ytce_equivalent),
        missing_gap=tuple(missing_gap),
        safe_absorption_boundary=safe_absorption_boundary,
        prohibited_behaviours=tuple(prohibited_behaviours),
        candidate_patch_id=candidate_patch_id,
        priority=priority,
        implementation_status=implementation_status,
    )


def build_external_reference_absorption_matrix() -> tuple[ExternalReferenceAbsorptionEntry, ...]:
    return (
        _entry(
            "GoFullPage 8.6_0.zip",
            "01_local_browser_extension_archives",
            ("GoFullPage 8.6_0.zip",),
            "full_page_screenshot_capture",
            ("viewport stepping", "full-page completion boundary", "capture progress state", "stable output naming"),
            ("twitter_capture_screenshot_preservation.py", "source_msn_rendered_browser_validation.py"),
            ("live browser stitch implementation remains adapter-specific",),
            "Reimplement full-page control flow and manifest ideas in YTCE; do not vendor extension assets.",
            ("browser extension packaging", "extension assets", "hidden tracking"),
            "V77A/V77D",
            "high",
            "PARTIAL",
        ),
        _entry(
            "PageCap 1.2.0_0.zip",
            "01_local_browser_extension_archives",
            ("PageCap 1.2.0_0.zip",),
            "page_capture_extension_reference",
            ("single-page capture workflow", "save/export status", "page metadata binding"),
            ("twitter_capture_screenshot_preservation.py", "source_local_webpage_viewer.py"),
            ("generic browser capture UI is not production generalized",),
            "Absorb capture manifest/status conventions only.",
            ("extension packaging", "remote upload", "tracking"),
            "V77A/V77D",
            "medium",
            "PARTIAL",
        ),
        _entry(
            "Twitter Exporter 0.8.58_0.zip",
            "01_local_browser_extension_archives",
            ("Twitter Exporter 0.8.58_0.zip",),
            "twitter_read_only_export_ui",
            ("export progress", "table-style review", "local export state", "media export intent"),
            ("twitter_capture_live_output_closeout_v77c.py", "twitter_capture_profile_media_provenance.py"),
            ("full GUI parity for account exports is not implemented",),
            "Absorb read-only export-state and review UI ideas; no account write actions.",
            ("posting", "deleting", "liking", "following", "unfollowing", "DMs", "credential automation"),
            "V77C/V77D",
            "high",
            "PARTIAL",
        ),
        _entry(
            "Video Download Helper 10.5.24.2_0.zip",
            "01_local_browser_extension_archives",
            ("Video Download Helper 10.5.24.2_0.zip",),
            "media_inventory_and_companion_architecture",
            ("capture/download job status", "media inventory manifest", "native companion boundary"),
            ("youtube_media_download_backend.py", "rendered_citation_recording_metadata_v77d.py"),
            ("generic source-preservation media capture runner is metadata-only in V77D",),
            "Use local descriptive metadata and allowed source preservation only.",
            ("DRM circumvention", "hidden protected-stream extraction", "license-server impersonation"),
            "V77D",
            "medium",
            "PARTIAL",
        ),
        _entry(
            "Video Downloader Professional 10.5.24.2_0.zip",
            "01_local_browser_extension_archives",
            ("Video Downloader Professional 10.5.24.2_0.zip",),
            "media_inventory_ui_reference",
            ("media list UI", "detected-media state", "download status wording"),
            ("youtube_gui_media_queue.py", "twitter_media_backend.py"),
            ("Twitter/X media remains shared-backend intent, not a separate downloader stack",),
            "Only source-reference preservation metadata and shared backend patterns are in scope.",
            ("DRM circumvention", "credential automation", "hidden stream extraction"),
            "V77D",
            "medium",
            "PARTIAL",
        ),
        _entry(
            "aclap-dev__vdhcoapp",
            "02_high_priority_source_refs",
            ("native companion files", "download bridge modules"),
            "native_media_companion",
            ("job state separation", "local companion boundary", "download status record"),
            ("jdownloader_internal_job.py", "youtube_media_download_backend.py"),
            ("no generic native media companion is added by V77D",),
            "Absorb state and boundary vocabulary; keep third-party companion code reference-only.",
            ("DRM circumvention", "protected-stream extraction"),
            "V77D+",
            "medium",
            "REFERENCE_ONLY",
        ),
        _entry(
            "alasim__video-downloader-pro",
            "02_high_priority_source_refs",
            ("extension downloader source",),
            "video_download_extension_reference",
            ("detected-media queue", "per-item status", "format labeling"),
            ("youtube_media_download_backend.py", "twitter_media_backend.py"),
            ("no generic browser media detector is implemented",),
            "Use only queue/status concepts for legal source-preservation workflows.",
            ("DRM bypass", "hidden extraction", "aggressive scraping"),
            "V77D+",
            "low",
            "REFERENCE_ONLY",
        ),
        _entry(
            "annismckenzie__x-article-exporter",
            "02_high_priority_source_refs",
            ("internal/extract/parse.go", "internal/images/download.go", "internal/pipeline/pipeline.go", "internal/render/html.go", "internal/render/pdf.go", "internal/validate/validate.go", "internal/jobs/manager.go"),
            "x_article_export_pipeline",
            ("article extraction model", "pipeline/job state", "rendered HTML/PDF sidecars", "URL validation", "image reference handling"),
            ("profile_media_article_extraction_adapter.py", "profile_media_home_source_folder_ingestion.py"),
            ("no full X article extraction or renderer parity", "no vendored fonts", "image download stays guarded/not automatic"),
            "Reimplement extraction/rendering schema ideas; do not copy fonts or Go implementation wholesale.",
            ("font vendoring", "unbounded image downloads", "credential automation"),
            "V76L/V77D+",
            "high",
            "PARTIAL",
        ),
        _entry(
            "Aston1690__baoyu-danger-x-to-markdown",
            "02_high_priority_source_refs",
            ("markdown export source",),
            "twitter_markdown_export",
            ("thread-to-markdown rendering", "quote/media reference formatting"),
            ("twitter_capture_live_output_closeout_v77c.py", "source_twitter_compact_row.py"),
            ("production post/thread markdown renderer is not complete",),
            "Absorb formatting ideas for read-only captured rows only.",
            ("credential automation", "write actions"),
            "V77D+",
            "medium",
            "REFERENCE_ONLY",
        ),
        _entry(
            "d60__twikit",
            "02_high_priority_source_refs",
            ("twikit docs", "twikit modules"),
            "twitter_client_library_reference",
            ("typed timeline/user model", "rate-limit status fields", "cursor data shapes"),
            ("twitter_browser_timeline_pagination.py", "twitter_timeline_cursor_scheduler.py"),
            ("no official/full client API wrapper is added",),
            "Use data-shape lessons only; YTCE remains read-only browser/session capture.",
            ("posting", "liking", "following", "DMs", "credential automation"),
            "V74/V77C",
            "medium",
            "PARTIAL",
        ),
        _entry(
            "eight04__web-exporter",
            "02_high_priority_source_refs",
            ("web exporter modules",),
            "web_export_state",
            ("local export package state", "HTML export review", "downloadable sidecars"),
            ("source_offline_bundle_writer.py", "source_local_webpage_viewer.py"),
            ("generic web-export GUI is not complete",),
            "Absorb local-only export summaries and manifest style.",
            ("automated login", "aggressive crawling"),
            "V77D+",
            "medium",
            "PARTIAL",
        ),
        _entry(
            "fa0311__twitter-openapi",
            "02_high_priority_source_refs",
            ("endpoint docs/source",),
            "twitter_internal_api_documentation",
            ("query name catalog", "timeline endpoint shape", "cursor variable schema"),
            ("twitter_browser_timeline_pagination.py", "twitter_capture_live_output_closeout_v77c.py"),
            ("no official API claim; no paid API integration",),
            "Use as read-only endpoint-shape reference for already captured browser responses.",
            ("write endpoints", "auth bypass", "rate-limit bypass"),
            "V74/V77C",
            "high",
            "PARTIAL",
        ),
        _entry(
            "fa0311__TwitterInternalAPIDocument",
            "02_high_priority_source_refs",
            ("operation docs", "GraphQL operation lists"),
            "twitter_internal_api_documentation",
            ("operation naming", "variables/features separation", "cursor boundaries"),
            ("twitter_browser_timeline_pagination.py", "tools/run_twitter_timeline_cursor_batch_v74h.py"),
            ("no broad endpoint crawler",),
            "Use for schema understanding; no automated endpoint expansion in V77D.",
            ("write endpoints", "forced retries", "credential automation"),
            "V74/V77C",
            "high",
            "PARTIAL",
        ),
        _entry(
            "fawwazabrials__TwitterFetch",
            "02_high_priority_source_refs",
            ("fetch helpers",),
            "twitter_fetch_reference",
            ("request templating", "response normalization", "error status propagation"),
            ("twitter_capture_live_output_closeout_v77c.py", "twitter_browser_timeline_pagination.py"),
            ("no live fetch expansion in V77D",),
            "Only normalize already captured local responses.",
            ("credential automation", "aggressive fetching"),
            "V77C",
            "medium",
            "PARTIAL",
        ),
        _entry(
            "prinsss__twitter-web-exporter",
            "02_high_priority_source_refs",
            ("src/components/modals/export-data.tsx", "src/components/modals/export-media.tsx", "src/core/database/manager.ts", "src/components/table/table-view.tsx", "src/modules/bookmarks", "src/modules/followers", "src/modules/following", "src/modules/likes", "src/modules/search-timeline", "src/modules/tweet-detail", "src/modules/user-media", "src/modules/user-tweets", "zip-stream/export utilities"),
            "twitter_exporter_ui_and_database",
            ("export-data/export-media UI", "database manager", "table views", "timeline modules", "zip stream/export utilities"),
            ("twitter_capture_live_output_closeout_v77c.py", "twitter_capture_profile_media_provenance.py"),
            ("full account export parity and GUI database table are not implemented",),
            "Absorb read-only export and review patterns; exclude private DM/write interaction modules.",
            ("posting", "deleting", "liking", "following", "unfollowing", "DMs", "credential automation"),
            "V77D+",
            "high",
            "PARTIAL",
        ),
        _entry(
            "RayanIJ__twitter-stream-proxy",
            "04_extra_source_refs",
            ("docker-compose.yml", "nginx.conf.template", "Dockerfile"),
            "proxy_architecture_reference",
            ("boundary/status reporting", "explicit proxy configuration flags"),
            ("twitter_capture_live_output_closeout_v77c.py", "rendered_citation_recording_metadata_v77d.py"),
            ("proxy architecture is restricted and not implemented",),
            "Only absorb the idea of explicit boundary status; do not implement proxy/evasion.",
            ("proxy rotation", "proxy/evasion", "evasion", "rate-limit bypass"),
            "V77D",
            "high",
            "UNSAFE_OUT_OF_SCOPE",
        ),
        _entry(
            "rxliuli__WebDataMaster",
            "02_high_priority_source_refs",
            ("web data/export modules",),
            "web_data_export_reference",
            ("table/export abstraction", "local dataset model", "task state"),
            ("profile_media_home_repository_model.py", "total_export_manifest.py"),
            ("not mapped to GUI dataset import yet",),
            "Absorb local data/export schema ideas only.",
            ("credential automation", "aggressive crawling"),
            "V77D+",
            "medium",
            "REFERENCE_ONLY",
        ),
        _entry(
            "rxliuli__xkit",
            "02_high_priority_source_refs",
            ("xkit source modules",),
            "twitter_helper_library_reference",
            ("timeline model", "export helpers", "request state"),
            ("twitter_timeline_cursor_scheduler.py", "twitter_capture_live_output_closeout_v77c.py"),
            ("no full xkit-equivalent helper layer",),
            "Absorb read-only schema ideas; no interaction automation.",
            ("write actions", "credential automation"),
            "V77D+",
            "medium",
            "PARTIAL",
        ),
        _entry(
            "sportiz91__x-monitor",
            "02_high_priority_source_refs",
            ("ops/timelines/surface modeling",),
            "twitter_monitor_model_reference",
            ("timeline/surface model", "cooldown-like monitoring state", "summary records"),
            ("twitter_timeline_cursor_scheduler.py", "twitter_capture_live_output_closeout_v77c.py"),
            ("no background monitor service is implemented",),
            "Use offline model ideas only; no autonomous monitoring in V77D.",
            ("aggressive monitoring", "rate-limit bypass", "credential automation"),
            "V77D+",
            "medium",
            "PARTIAL",
        ),
        _entry(
            "yashiels__twitter-cli",
            "02_high_priority_source_refs",
            ("CLI modules",),
            "twitter_cli_reference",
            ("command summaries", "local export flags", "resume state presentation"),
            ("tools/run_twitter_capture_live_output_closeout_cli_v77c.py", "tools/run_rendered_citation_recording_metadata_cli_v77d.py"),
            ("no broad Twitter CLI command set",),
            "Absorb CLI output clarity; keep offline/read-only boundaries.",
            ("posting", "deleting", "following", "credential automation"),
            "V77D",
            "low",
            "PARTIAL",
        ),
        _entry(
            "kdippan__SnapStream",
            "04_extra_source_refs",
            ("manifest.json", "offline.html", "index.html", "api/contact.js"),
            "offline_media_site_reference",
            ("offline fallback page", "manifest metadata", "static local review surfaces"),
            ("source_local_webpage_viewer.py", "source_replay_static_snapshot.py"),
            ("not a capture engine in YTCE",),
            "Absorb local/offline review page wording and manifest hints only.",
            ("ad/tracking assets", "unrelated site deployment"),
            "V77D+",
            "low",
            "REFERENCE_ONLY",
        ),
        _entry(
            "myselfshravan__third-eye",
            "04_extra_source_refs",
            ("src/capture/capture.ts", "src/capture/readiness.ts", "src/capture/browserPool.ts", "src/api/routes/screenshot.ts", "src/queue/queue.ts", "src/storage/storage.ts"),
            "capture_api_and_queue_reference",
            ("readiness checks", "job queue state", "storage provider separation", "blocked capture status"),
            ("twitter_capture_screenshot_preservation.py", "rendered_citation_recording_metadata_v77d.py"),
            ("no API server or browser pool added",),
            "Absorb status/queue/readiness models; V77D records metadata only.",
            ("web crawling", "remote screenshot API", "proxy/evasion"),
            "V77D+",
            "high",
            "PARTIAL",
        ),
        _entry(
            "paulrouget__pathfinder",
            "04_extra_source_refs",
            ("partitioner/src/partitioner.rs", "demo/client/src/renderer.ts", "font-renderer"),
            "rendering_engine_reference",
            ("tiling/partitioning concepts", "render completion checks"),
            ("twitter_capture_screenshot_preservation.py"),
            ("no rendering engine integration planned",),
            "Only high-level tiling/completion concepts are relevant; do not vendor renderer/font code.",
            ("font/code vendoring", "renderer replacement"),
            "V77D+",
            "low",
            "REFERENCE_ONLY",
        ),
        _entry(
            "paulrouget__webcc",
            "04_extra_source_refs",
            ("schema.def", "docs/api/dom.md", "docs/api/canvas.md", "docs/api/fetch.md", "include/webcc/webcc.h"),
            "browser_runtime_api_reference",
            ("capability taxonomy", "DOM/canvas/fetch boundary naming"),
            ("PROJECT_CURRENT_CAPABILITIES_AND_FUNCTIONS_V76M.md", "rendered_citation_recording_metadata_v77d.py"),
            ("no runtime binding or WebCC integration",),
            "Use vocabulary for capability boundaries only.",
            ("runtime embedding", "network fetch expansion"),
            "V77D+",
            "low",
            "REFERENCE_ONLY",
        ),
        _entry(
            "copperline-labs__rendex-mcp",
            "04_extra_source_refs",
            ("src/tools/screenshot.ts", "src/tools/extract.ts", "src/tools/watch.ts", "src/lib/preview.ts", "src/oauth"),
            "mcp_screenshot_extract_reference",
            ("tool schema design", "preview/status model", "screenshot/extract command separation"),
            ("tools/run_rendered_citation_recording_metadata_cli_v77d.py"),
            ("no MCP server is added",),
            "Absorb CLI/tool schema separation only; OAuth pieces are out of scope.",
            ("credential automation", "remote MCP deployment"),
            "V77D+",
            "medium",
            "REFERENCE_ONLY",
        ),
        _entry(
            "kubahorak__pagecap",
            "04_extra_source_refs",
            ("main.go", "internal/browser/browser.go", "internal/handler/handler.go", "internal/handler/templates/index.html"),
            "page_capture_service_reference",
            ("browser launch separation", "handler/request state", "capture parameters"),
            ("twitter_capture_screenshot_preservation.py", "lightweight_in_app_browser_capture.py"),
            ("no capture service is introduced in V77D",),
            "Absorb parameter/status conventions only.",
            ("remote screenshot service", "unbounded crawling"),
            "V77D+",
            "medium",
            "PARTIAL",
        ),
        _entry(
            "mrcoles__full-page-screen-capture-chrome-extension",
            "04_extra_source_refs",
            ("api.js", "page.js", "popup.js", "manifest.json", "screenshots/active-screenshot.png", "screenshots/finished-screenshot.png"),
            "full_page_screenshot_stitch_reference",
            ("scroll/clip stepping", "active/finished capture status", "popup progress state"),
            ("twitter_capture_screenshot_preservation.py"),
            ("live stitch remains adapter-specific",),
            "Reimplement scroll/clip planning; do not copy extension assets or packaging.",
            ("extension asset vendoring", "extension packaging wholesale"),
            "V77A/V77D",
            "high",
            "PARTIAL",
        ),
        _entry(
            "EverythingSuckz__webshot-api",
            "04_extra_source_refs",
            ("lib/api.dart", "lib/browser.dart", "lib/screen_shot.dart", "test/webshot_api_test.dart"),
            "webshot_api_reference",
            ("API status model", "browser/screenshot separation", "testable capture result"),
            ("twitter_capture_screenshot_preservation.py", "rendered_citation_recording_metadata_v77d.py"),
            ("no remote webshot service is implemented",),
            "Absorb local manifest/status fields only.",
            ("remote capture service", "unbounded fetch", "proxy/evasion"),
            "V77D+",
            "medium",
            "PARTIAL",
        ),
        _entry(
            "sea-deep__link-to-screenshot",
            "04_extra_source_refs",
            ("src/browserManager.js", "src/capture.js", "src/utils.js", "bin/cli.js", "tests/screenshot.test.js"),
            "link_to_screenshot_cli_reference",
            ("CLI capture arguments", "browser manager boundary", "screenshot output tests"),
            ("tools/run_twitter_capture_screenshot_preservation_cli_v77a.py", "tools/run_rendered_citation_recording_metadata_cli_v77d.py"),
            ("no live screenshot CLI expansion in V77D",),
            "Absorb CLI and manifest patterns; V77D remains metadata-only.",
            ("automated crawling", "remote capture", "proxy/evasion"),
            "V77D+",
            "medium",
            "PARTIAL",
        ),
        _entry(
            "stratofax__pagecap",
            "04_extra_source_refs",
            ("pagecap/__main__.py", "pagecap/pagecap_metadata.py"),
            "python_page_capture_reference",
            ("Python CLI shape", "capture metadata", "dependency boundary"),
            ("twitter_capture_screenshot_preservation.py", "tools/run_rendered_citation_recording_metadata_cli_v77d.py"),
            ("no generic Playwright screenshot executor is added in V77D",),
            "Absorb Python metadata shape; do not add new browser dependency behavior.",
            ("remote capture service", "unbounded crawling"),
            "V77D+",
            "medium",
            "PARTIAL",
        ),
    )


def matrix_to_dict(entries: Iterable[ExternalReferenceAbsorptionEntry] | None = None) -> dict[str, Any]:
    rows = tuple(entries or build_external_reference_absorption_matrix())
    return {
        "schema_version": EXTERNAL_REFERENCE_ABSORPTION_SCHEMA_VERSION,
        "reference_count": len(rows),
        "rows": [entry.to_dict() for entry in rows],
        "safety_invariants": {
            "do_not_vendor_external_repos": True,
            "no_browser_launch": True,
            "no_network": True,
            "no_media_download": True,
            "no_drm_circumvention": True,
            "no_captcha_solver": True,
            "human_mediated_access_challenge_allowed": True,
            "no_proxy_or_evasion": True,
            "no_x_twitter_write_actions": True,
        },
    }


def summarize_absorption_matrix(entries: Iterable[ExternalReferenceAbsorptionEntry] | None = None) -> dict[str, Any]:
    rows = tuple(entries or build_external_reference_absorption_matrix())
    by_status: dict[str, int] = {}
    by_priority: dict[str, int] = {}
    for entry in rows:
        by_status[entry.implementation_status] = by_status.get(entry.implementation_status, 0) + 1
        by_priority[entry.priority] = by_priority.get(entry.priority, 0) + 1
    return {
        "schema_version": EXTERNAL_REFERENCE_ABSORPTION_SCHEMA_VERSION,
        "reference_count": len(rows),
        "statuses": by_status,
        "priorities": by_priority,
        "unsafe_out_of_scope": [entry.reference_name for entry in rows if entry.implementation_status == "UNSAFE_OUT_OF_SCOPE"],
        "high_priority": [entry.reference_name for entry in rows if entry.priority == "high"],
    }


def inspect_reference_paths(reference_root: str | Path) -> dict[str, Any]:
    root = Path(reference_root)
    entries = build_external_reference_absorption_matrix()
    groups = sorted({entry.reference_group for entry in entries})
    return {
        "schema_version": EXTERNAL_REFERENCE_ABSORPTION_SCHEMA_VERSION,
        "reference_root": str(root),
        "reference_root_exists": root.exists(),
        "groups": [
            {
                "reference_group": group,
                "exists": (root / group).exists(),
            }
            for group in groups
        ],
        "repo_reference_inventory_scan": True,
        "web_download_performed": False,
        "media_download_performed": False,
        "browser_launch_performed": False,
    }
