from source_adapter_keys_accounts_credential_reference_runtime import example_keys_accounts_credential_reference_runtime_package
from source_adapter_keys_accounts_credential_reference_runtime_verifier import verify_source_adapter_keys_accounts_credential_reference_runtime_package

v = verify_source_adapter_keys_accounts_credential_reference_runtime_package(example_keys_accounts_credential_reference_runtime_package())
assert v["verified"], v
assert v["issue_count"] == 0, v
print("Source Adapter KEYS/ACCOUNTS Credential Reference Runtime verifier self-test passed.")
