from source_adapter_provider_error_receipt_normalizer_runtime import example_source_adapter_provider_error_receipt_normalizer_runtime_package
from source_adapter_provider_error_receipt_normalizer_runtime_verifier import verify_source_adapter_provider_error_receipt_normalizer_runtime

package = example_source_adapter_provider_error_receipt_normalizer_runtime_package()
verified = verify_source_adapter_provider_error_receipt_normalizer_runtime(package)
assert verified["verified"], verified
broken = dict(package)
broken["status"] = "BROKEN"
assert not verify_source_adapter_provider_error_receipt_normalizer_runtime(broken)["verified"]
print("Source Adapter Provider Error Receipt Normalizer Runtime verifier self-test passed.")
