from source_adapter_keys_accounts_provider_onboarding_runtime import example_source_adapter_keys_accounts_provider_onboarding_runtime_package
from source_adapter_keys_accounts_provider_onboarding_runtime_verifier import verify_source_adapter_keys_accounts_provider_onboarding_runtime

package = example_source_adapter_keys_accounts_provider_onboarding_runtime_package()
verified = verify_source_adapter_keys_accounts_provider_onboarding_runtime(package)
assert verified["verified"], verified
broken = dict(package)
broken["status"] = "BROKEN"
assert not verify_source_adapter_keys_accounts_provider_onboarding_runtime(broken)["verified"]
print("Source Adapter KEYS Accounts Provider Onboarding Runtime verifier self-test passed.")
