from source_adapter_keys_accounts_catalogue_search_runtime import example_source_adapter_keys_accounts_catalogue_search_runtime_package
from source_adapter_keys_accounts_catalogue_search_runtime_verifier import verify_source_adapter_keys_accounts_catalogue_search_runtime

package = example_source_adapter_keys_accounts_catalogue_search_runtime_package()
verified = verify_source_adapter_keys_accounts_catalogue_search_runtime(package)
assert verified["verified"], verified
broken = dict(package)
broken["status"] = "BROKEN"
assert not verify_source_adapter_keys_accounts_catalogue_search_runtime(broken)["verified"]
print("Source Adapter KEYS Accounts Catalogue Search Runtime verifier self-test passed.")
