from source_adapter_named_site_profile_store_runtime import example_source_adapter_named_site_profile_store_runtime_package
from source_adapter_named_site_profile_store_runtime_verifier import verify_source_adapter_named_site_profile_store_runtime_package

verification = verify_source_adapter_named_site_profile_store_runtime_package(example_source_adapter_named_site_profile_store_runtime_package())
assert verification["verified"], verification
assert verification["issue_count"] == 0, verification
print("Source Adapter Named-Site Profile Store Runtime verifier self-test passed.")
