from source_adapter_operator_acceptance_checklist_runtime import example_source_adapter_operator_acceptance_checklist_runtime_package
from source_adapter_operator_acceptance_checklist_runtime_verifier import verify_source_adapter_operator_acceptance_checklist_runtime

package = example_source_adapter_operator_acceptance_checklist_runtime_package()
verified = verify_source_adapter_operator_acceptance_checklist_runtime(package)
assert verified["verified"], verified
broken = dict(package)
broken["status"] = "BROKEN"
assert not verify_source_adapter_operator_acceptance_checklist_runtime(broken)["verified"]
print("Source Adapter Operator Acceptance Checklist Runtime verifier self-test passed.")
