from source_adapter_total_export_receipt_index_runtime import example_source_adapter_total_export_receipt_index_runtime_package
from source_adapter_total_export_receipt_index_runtime_verifier import verify_source_adapter_total_export_receipt_index_runtime_package

verification = verify_source_adapter_total_export_receipt_index_runtime_package(example_source_adapter_total_export_receipt_index_runtime_package())
assert verification["verified"], verification
assert verification["issue_count"] == 0, verification
print("Source Adapter Total Export Receipt Index Runtime verifier self-test passed.")
