from source_adapter_msn_shadow_dom_profile_verifier_runtime import example_source_adapter_msn_shadow_dom_profile_verifier_runtime_package
from source_adapter_msn_shadow_dom_profile_verifier_runtime_verifier import verify_source_adapter_msn_shadow_dom_profile_verifier_runtime

package = example_source_adapter_msn_shadow_dom_profile_verifier_runtime_package()
verified = verify_source_adapter_msn_shadow_dom_profile_verifier_runtime(package)
assert verified["verified"], verified
broken = dict(package)
broken["status"] = "BROKEN"
assert not verify_source_adapter_msn_shadow_dom_profile_verifier_runtime(broken)["verified"]
print("Source Adapter MSN Shadow DOM Profile Verifier Runtime verifier self-test passed.")
