from source_adapter_external_archive_provider_adapter_runtime import example_source_adapter_external_archive_provider_adapter_runtime_package
from source_adapter_external_archive_provider_adapter_runtime_verifier import verify_source_adapter_external_archive_provider_adapter_runtime

package = example_source_adapter_external_archive_provider_adapter_runtime_package()
verified = verify_source_adapter_external_archive_provider_adapter_runtime(package)
assert verified["verified"], verified
broken = dict(package)
broken["status"] = "BROKEN"
assert not verify_source_adapter_external_archive_provider_adapter_runtime(broken)["verified"]
print("Source Adapter External Archive Provider Adapter Runtime verifier self-test passed.")
