from source_adapter_browser_automation_command_writer_runtime import example_source_adapter_browser_automation_command_writer_runtime_package
from source_adapter_browser_automation_command_writer_runtime_verifier import verify_source_adapter_browser_automation_command_writer_runtime

package = example_source_adapter_browser_automation_command_writer_runtime_package()
verified = verify_source_adapter_browser_automation_command_writer_runtime(package)
assert verified["verified"], verified
broken = dict(package)
broken["status"] = "BROKEN"
assert not verify_source_adapter_browser_automation_command_writer_runtime(broken)["verified"]
print("Source Adapter Browser Automation Command Writer Runtime verifier self-test passed.")
