from source_adapter_final_release_readiness_report_runtime import example_source_adapter_final_release_readiness_report_runtime_package
from source_adapter_final_release_readiness_report_runtime_verifier import verify_source_adapter_final_release_readiness_report_runtime

package = example_source_adapter_final_release_readiness_report_runtime_package()
verified = verify_source_adapter_final_release_readiness_report_runtime(package)
assert verified["verified"], verified
broken = dict(package)
broken["status"] = "BROKEN"
assert not verify_source_adapter_final_release_readiness_report_runtime(broken)["verified"]
print("Source Adapter Final Release Readiness Report Runtime verifier self-test passed.")
