from source_adapter_execution_policy_engine import example_source_adapter_execution_policy_engine_package
from source_adapter_execution_policy_engine_verifier import verify_source_adapter_execution_policy_engine_package

verification = verify_source_adapter_execution_policy_engine_package(example_source_adapter_execution_policy_engine_package())
assert verification["verified"], verification
assert verification["issue_count"] == 0, verification
print("Source Adapter Execution Policy Engine verifier self-test passed.")
