from source_adapter_keys_accounts_added_provider_registry_runtime import example_source_adapter_keys_accounts_added_provider_registry_runtime_package
from source_adapter_keys_accounts_added_provider_registry_runtime_verifier import verify_source_adapter_keys_accounts_added_provider_registry_runtime

package = example_source_adapter_keys_accounts_added_provider_registry_runtime_package()
verified = verify_source_adapter_keys_accounts_added_provider_registry_runtime(package)
assert verified["verified"], verified
broken = dict(package)
broken["status"] = "BROKEN"
assert not verify_source_adapter_keys_accounts_added_provider_registry_runtime(broken)["verified"]
print("Source Adapter KEYS Accounts Added Provider Registry Runtime verifier self-test passed.")
