from source_adapter_provider_receipt_schema_matrix_runtime import example_source_adapter_provider_receipt_schema_matrix_runtime_package
from source_adapter_provider_receipt_schema_matrix_runtime_verifier import verify_source_adapter_provider_receipt_schema_matrix_runtime

package = example_source_adapter_provider_receipt_schema_matrix_runtime_package()
verified = verify_source_adapter_provider_receipt_schema_matrix_runtime(package)
assert verified["verified"], verified
broken = dict(package)
broken["status"] = "BROKEN"
assert not verify_source_adapter_provider_receipt_schema_matrix_runtime(broken)["verified"]
print("Source Adapter Provider Receipt Schema Matrix Runtime verifier self-test passed.")
