from source_adapter_runbook_script_materialization_runtime import example_source_adapter_runbook_script_materialization_runtime_package
from source_adapter_runbook_script_materialization_runtime_verifier import verify_source_adapter_runbook_script_materialization_runtime

package = example_source_adapter_runbook_script_materialization_runtime_package()
verified = verify_source_adapter_runbook_script_materialization_runtime(package)
assert verified["verified"], verified
broken = dict(package)
broken["status"] = "BROKEN"
assert not verify_source_adapter_runbook_script_materialization_runtime(broken)["verified"]
print("Source Adapter Runbook Script Materialization Runtime verifier self-test passed.")
