from source_adapter_gui_evidence_queue_command_bridge_runtime import example_source_adapter_gui_evidence_queue_command_bridge_runtime_package
from source_adapter_gui_evidence_queue_command_bridge_runtime_verifier import verify_source_adapter_gui_evidence_queue_command_bridge_runtime

package = example_source_adapter_gui_evidence_queue_command_bridge_runtime_package()
verified = verify_source_adapter_gui_evidence_queue_command_bridge_runtime(package)
assert verified["verified"], verified
broken = dict(package)
broken["status"] = "BROKEN"
assert not verify_source_adapter_gui_evidence_queue_command_bridge_runtime(broken)["verified"]
print("Source Adapter GUI Evidence Queue Command Bridge Runtime verifier self-test passed.")
