from source_adapter_release_manifest_signing_runtime import example_source_adapter_release_manifest_signing_runtime_package
from source_adapter_release_manifest_signing_runtime_verifier import verify_source_adapter_release_manifest_signing_runtime_package

verification = verify_source_adapter_release_manifest_signing_runtime_package(example_source_adapter_release_manifest_signing_runtime_package())
assert verification["verified"], verification
assert verification["issue_count"] == 0, verification
print("Source Adapter Release Manifest Signing Runtime verifier self-test passed.")
