from source_adapter_archive_manual_receipt_validator_runtime import example_source_adapter_archive_manual_receipt_validator_runtime_package
from source_adapter_archive_manual_receipt_validator_runtime_verifier import verify_source_adapter_archive_manual_receipt_validator_runtime

package = example_source_adapter_archive_manual_receipt_validator_runtime_package()
verified = verify_source_adapter_archive_manual_receipt_validator_runtime(package)
assert verified["verified"], verified
broken = dict(package)
broken["status"] = "BROKEN"
assert not verify_source_adapter_archive_manual_receipt_validator_runtime(broken)["verified"]
print("Source Adapter Archive Manual Receipt Validator Runtime verifier self-test passed.")
