from pathlib import Path
text = Path("SOURCE_ADAPTER_OPERATOR_DELIVERY_RECEIPT_CLOSEOUT.md").read_text(encoding="utf-8")
for phrase in [
    "SOURCE_ADAPTER_OPERATOR_DELIVERY_RECEIPT_CLOSEOUT_BUILT",
    "SOURCE_ADAPTER_OPERATOR_DELIVERY_RECEIPTS_REVIEWED",
    "SOURCE_ADAPTER_OPERATOR_DELIVERY_ACCEPTANCE_MATRIX_READY",
    "SOURCE_ADAPTER_OPERATOR_DELIVERY_RELEASE_GATE_READY",
    "SOURCE_ADAPTER_OPERATOR_DELIVERY_RECEIPT_CLOSEOUT_READY_FOR_RELEASE_SECTION_COMPLETION",
    "KEYS/ACCOUNTS",
]:
    assert phrase in text, phrase
print("Source Adapter Operator Delivery Receipt Closeout docs self-test passed.")
