from source_adapter_operator_final_runbook_dispatch_runtime import example_source_adapter_operator_final_runbook_dispatch_runtime_package
from source_adapter_operator_final_runbook_dispatch_runtime_verifier import verify_source_adapter_operator_final_runbook_dispatch_runtime

package = example_source_adapter_operator_final_runbook_dispatch_runtime_package()
verified = verify_source_adapter_operator_final_runbook_dispatch_runtime(package)
assert verified["verified"], verified
broken = dict(package)
broken["status"] = "BROKEN"
assert not verify_source_adapter_operator_final_runbook_dispatch_runtime(broken)["verified"]
print("Source Adapter Operator Final Runbook Dispatch Runtime verifier self-test passed.")
