from source_adapter_evidence_source_package_builder_runtime import example_source_adapter_evidence_source_package_builder_runtime_package
from source_adapter_evidence_source_package_builder_runtime_verifier import verify_source_adapter_evidence_source_package_builder_runtime

package = example_source_adapter_evidence_source_package_builder_runtime_package()
verified = verify_source_adapter_evidence_source_package_builder_runtime(package)
assert verified["verified"], verified
broken = dict(package)
broken["status"] = "BROKEN"
assert not verify_source_adapter_evidence_source_package_builder_runtime(broken)["verified"]
print("Source Adapter Evidence Source Package Builder Runtime verifier self-test passed.")
