from source_adapter_keys_accounts_visible_provider_runtime import example_source_adapter_keys_accounts_visible_provider_runtime_package
from source_adapter_keys_accounts_visible_provider_runtime_verifier import verify_source_adapter_keys_accounts_visible_provider_runtime

package = example_source_adapter_keys_accounts_visible_provider_runtime_package()
verified = verify_source_adapter_keys_accounts_visible_provider_runtime(package)
assert verified["verified"], verified
broken = dict(package)
broken["status"] = "BROKEN"
assert not verify_source_adapter_keys_accounts_visible_provider_runtime(broken)["verified"]
print("Source Adapter KEYS Accounts Visible Provider Runtime verifier self-test passed.")
