from source_adapter_full_execution_integration_bundle_closeout import example_full_execution_integration_bundle_closeout_package
from source_adapter_full_execution_integration_bundle_closeout_verifier import verify_source_adapter_full_execution_integration_bundle_closeout_package

v = verify_source_adapter_full_execution_integration_bundle_closeout_package(example_full_execution_integration_bundle_closeout_package())
assert v["verified"], v
assert v["issue_count"] == 0, v
print("Source Adapter Full Execution Integration Bundle Closeout verifier self-test passed.")
