from source_adapter_execution_policy_bundle_closeout import example_source_adapter_execution_policy_bundle_closeout_package
from source_adapter_execution_policy_bundle_closeout_verifier import verify_source_adapter_execution_policy_bundle_closeout_package

verification = verify_source_adapter_execution_policy_bundle_closeout_package(example_source_adapter_execution_policy_bundle_closeout_package())
assert verification["verified"], verification
assert verification["issue_count"] == 0, verification
print("Source Adapter Execution Policy Bundle Closeout verifier self-test passed.")
