from source_adapter_provider_execution_dispatcher_runtime import example_source_adapter_provider_execution_dispatcher_runtime_package
from source_adapter_provider_execution_dispatcher_runtime_verifier import verify_source_adapter_provider_execution_dispatcher_runtime

package = example_source_adapter_provider_execution_dispatcher_runtime_package()
verified = verify_source_adapter_provider_execution_dispatcher_runtime(package)
assert verified["verified"], verified
broken = dict(package)
broken["status"] = "BROKEN"
assert not verify_source_adapter_provider_execution_dispatcher_runtime(broken)["verified"]
print("Source Adapter Provider Execution Dispatcher Runtime verifier self-test passed.")
