@echo off
setlocal
cd /d "%~dp0..\.."
echo [R42EL] Running review-style file converter held-row smoke. No GUI/WebView2/archive.ph/network.
call tools\profile_media_file_converter\_r42ei_python.cmd -m py_compile main.py profile_media_file_converter_r42eh.py profile_media_file_converter_r42eg.py profile_media_file_converter_r42eh_test.py || exit /b 1
call tools\profile_media_file_converter\_r42ei_python.cmd profile_media_file_converter_r42eh_test.py || exit /b 1
echo [R42EL] Checking Review-fillbox/FIlE Converter markers...
call tools\profile_media_file_converter\_r42ei_python.cmd -c "from pathlib import Path; import json; s=Path('main.py').read_text(encoding='utf-8', errors='replace'); checks={'files_tickbox_restored':'session_file_selected_paths' in s and 'def _toggle_session_file_selected' in s and 'self.session_file_select_widgets' in s,'files_tickbox_not_converter_queue':'FILES tickbox is a normal multi-select/highlight control, not a converter queue switch' in s,'k_only_inside_converter':'def _toggle_session_file_keep_original_from_converter' in s and 'text=\"K\"' in s and 'no converter checkbox, queue arrow, or K button on FILES rows' not in s,'held_rows_scroll_frame':'self.file_converter_drop_list_frame = ctk.CTkScrollableFrame' in s and 'height=150' in s,'held_rows_not_plain_log':'self.file_converter_queue_textbox = None' in s and 'Review-style rows, not a plain activity log' in s,'per_item_dropdowns':'def _file_converter_item_target_var_for_path' in s and 'def _file_converter_set_item_target' in s and 'values=allowed' in s,'global_convert_to_selected_only':'def _file_converter_apply_global_format_to_selected' in s and 'Convert-to applies to selected held rows' in s,'convert_only_selected_held_rows':'selected_paths = [path for path in queued if path in selected_set]' in s and 'Tick one or more held File Converter rows' in s,'take_all_compact':'text=\"Take all\"' in s and 'text=\"Take all:\"' not in s,'drag_hover_converter_animation':'session_file_drag_over_converter' in s and 'Release to hold' in s and 'selected FILES item(s)' in s,'multi_drag_selected_files':'def _selected_session_file_paths_for_drag' in s and 'self.session_file_drag_source_paths' in s,'r42el_marker':'R42EL_REVIEW_STYLE_FILE_CONVERTER_ROWS' in s}; print(json.dumps(checks, indent=2)); raise SystemExit(0 if all(checks.values()) else 1)" || exit /b 1
echo [DONE] R42EL smoke passed.
