@echo off
setlocal
cd /d "%~dp0..\.."
echo [R42EN] Running Review-fillbox clone / text rename smoke. No GUI/WebView2/archive.ph/network.
call tools\profile_media_file_converter\_r42ei_python.cmd -m py_compile main.py profile_media_file_converter_r42eh.py profile_media_file_converter_r42eg.py profile_media_file_converter_r42eh_test.py || exit /b 1
call tools\profile_media_file_converter\_r42ei_python.cmd profile_media_file_converter_r42eh_test.py || exit /b 1
echo [R42EN] Checking actual Review-style fillbox clone markers...
call tools\profile_media_file_converter\_r42ei_python.cmd -c "from pathlib import Path; import json; s=Path('main.py').read_text(encoding='utf-8', errors='replace'); checks={'review_db_source_pattern_present':'source_review_selected_keys' in s and '_toggle_source_review_select_all' in s and 'claim_source_review_fillbox' in s,'converter_uses_master_child_glyphs':'R42EN_REVIEW_FILLBOX_CLONE' in s and '_file_converter_toggle_master_fillbox' in s and '_file_converter_toggle_item_fillbox' in s and 'file_converter_master_fillbox_button' in s,'converter_not_ctkcheckbox_for_held_rows':'file_converter_item_fillbox_buttons' in s and 'ctk.CTkCheckBox(\n                row,' not in s,'mixed_hold_allowed':'holding can be mixed; only a Convert run must be one kind' in s and 'File Converter holds {len(self.file_converter_queued_paths)} {mixed_text}' in s,'take_all_auto_all_supported':'Took {len(paths)} {\'supported\' if requested == \'auto\' else requested}' in s and 'Take all:auto needs only one FILES type' not in s,'global_format_selected_kind':'_file_converter_selected_kind_for_global_format' in s and 'Mixed selected\n        # kinds expose only auto' in s,'k_icon_in_converter':'session_keep_file_icon_image' in s and 'file_converter_item_keep_buttons' in s and 'text\": \"\" if getattr(self, \"session_keep_file_icon_image\", None)' in s,'k_no_rebuild':'K/keep-original toggles in place; it must not rebuild' in s,'drag_ghost':'_show_session_file_drag_ghost' in s and '_move_session_file_drag_ghost' in s and 'cursor-following drag ghost' in s,'rename_no_focusout_commit':'never commit a rename on FocusOut' in s and 'Enter/✓' in s and 'Esc/×' in s,'text_editor_focus_fix':'_focus_loaded_text_editor' in s and 'click-to-focus guard' in s}; print(json.dumps(checks, indent=2)); raise SystemExit(0 if all(checks.values()) else 1)" || exit /b 1
echo [DONE] R42EN smoke passed.
