@echo off
setlocal
cd /d "%~dp0..\.."
echo [R42EO] Running file converter compression UI/media-window smoke. No GUI/WebView2/archive.ph/network.
call tools\profile_media_file_converter\_r42ei_python.cmd -m py_compile main.py profile_media_file_converter_r42eh.py profile_media_file_converter_r42eg.py profile_media_file_converter_r42eh_test.py || exit /b 1
call tools\profile_media_file_converter\_r42ei_python.cmd profile_media_file_converter_r42eh_test.py || exit /b 1
echo [R42EO] Checking compression UI/media-window markers...
call tools\profile_media_file_converter\_r42ei_python.cmd -c "from pathlib import Path; import json, tempfile; from profile_media_file_converter_r42eh import plan_conversion; s=Path('main.py').read_text(encoding='utf-8', errors='replace'); tmp=Path(tempfile.mkdtemp(prefix='r42eo_smoke_')); img=tmp/'sample.png'; img.write_bytes(b'not-real-image-but-plan-only'); aud=tmp/'sample.wav'; aud.write_bytes(b'not-real-audio-but-plan-only'); checks={'video_audio_keep_original':'id=\"convertKeep\"' in s and 'Video/audio conversion target' in s,'add_files_neutral_hover':'neutral-file-intake' in s and 'button.neutral-file-intake:hover' in s,'no_auto_converted_groups':'do not create automatic Converted: groups' in s and 'session_file_conversion_groups = {}' in s,'drop_placeholder_hidden_when_held':'drop_label.pack_forget()' in s and 'if self.file_converter_queued_paths' in s,'flat_glyph_fillboxes':'R42EO_REVIEW_FILLBOX_FLAT' in s and 'ctk.CTkLabel(\n            master_row' in s and 'ctk.CTkLabel(\n                row' in s,'k_new_icon':'Keep icon icons8-k-ios-27-filled.png' in s,'c_icon_and_toggle':'Compression icon icons8-c-ios-27-filled.png' in s and '_toggle_session_file_compress_from_converter' in s,'compression_settings_window':'_open_file_converter_compression_settings_window' in s and 'Compression settings' in s,'backend_accepts_compress':'compress: bool = False' in Path('profile_media_file_converter_r42eh.py').read_text(encoding='utf-8', errors='replace')}; img_plan=plan_conversion(img,'webp',keep_original=True,compress=True,image_quality=60,image_max_dimension=4000,file_suffix='_compressed'); aud_plan=plan_conversion(aud,'mp3',keep_original=True,compress=True,audio_bitrate='128k'); checks['image_compress_plan']='_compressed.webp' in img_plan['output_path'] and img_plan['preset'].get('compress') is True and '-quality' in img_plan['command']; checks['audio_compress_plan']=aud_plan['preset'].get('compress') is True and '128k' in aud_plan['command']; print(json.dumps(checks, indent=2)); raise SystemExit(0 if all(checks.values()) else 1)" || exit /b 1
echo [DONE] R42EO smoke passed.
