@echo off
setlocal
cd /d "%~dp0..\.."
echo [R42EJ] Running file converter fill-box workflow smoke tests. No GUI/WebView2/archive.ph/network.
call tools\profile_media_file_converter\_r42ei_python.cmd -m py_compile main.py profile_media_file_converter_r42eh.py profile_media_file_converter_r42eg.py profile_media_file_converter_r42eh_test.py || exit /b 1
call tools\profile_media_file_converter\_r42ei_python.cmd profile_media_file_converter_r42eh_test.py || exit /b 1
echo [R42EJ] Checking fill-box workflow markers...
call tools\profile_media_file_converter\_r42ei_python.cmd -c "from pathlib import Path; import json; s=Path('main.py').read_text(encoding='utf-8', errors='replace'); checks={'files_row_arrow_convert_removed':'text=\"↔\"' not in s,'files_row_fillbox_selector':'session_file_converter_selected_paths' in s and '_toggle_file_converter_file_selection_from_checkbox' in s,'add_selected_files_button_removed':'Add selected FILES' not in s,'add_active_media_button_removed':'Add active media' not in s,'converter_drop_not_files_intake':'_file_converter_add_paths(paths, add_to_session=False, select_first=False, source_label=\"converter drop\")' in s,'same_type_enforced':'_file_converter_selection_compatible' in s and 'one file type per run' in s,'target_dropdown_family_filtered':'_file_converter_target_formats_for_kind' in s and '[\"auto\", \"mp4\", \"mkv\", \"webm\", \"mov\"]' in s,'open_folder_icon_loaded':'file_converter_open_folder_icon_image' in s and 'Open folder icon icons8-opened-folder-ios-27-outlined.png' in s,'conversion_group_not_folder':'session_file_conversion_groups' in s and 'Converted:' in s,'converter_textbox_not_activity_log':'uses its textbox as an item list, not an activity log' in s,'media_windows_keep_convert_selected':'_download_webpage_image_resource_ids_to_files_and_convert' in s and '_download_webpage_video_audio_resource_ids_to_files_and_convert' in s}; print(json.dumps(checks, indent=2)); raise SystemExit(0 if all(checks.values()) else 1)" || exit /b 1
echo [DONE] R42EJ smoke passed.
