@echo off
setlocal
cd /d "%~dp0..\.."
echo [R42EK] Running file converter window/FILES cleanup smoke. No GUI/WebView2/archive.ph/network.
call tools\profile_media_file_converter\_r42ei_python.cmd -m py_compile main.py profile_media_file_converter_r42eh.py profile_media_file_converter_r42eg.py profile_media_file_converter_r42eh_test.py || exit /b 1
call tools\profile_media_file_converter\_r42ei_python.cmd profile_media_file_converter_r42eh_test.py || exit /b 1
echo [R42EK] Checking window/FILES cleanup markers...
call tools\profile_media_file_converter\_r42ei_python.cmd -c "from pathlib import Path; import json; s=Path('main.py').read_text(encoding='utf-8', errors='replace'); checks={'files_rows_no_converter_checkbox':'converter_checkbox = ctk.CTkCheckBox' not in s,'files_rows_no_k_button':'keep_button = ctk.CTkButton(row_frame' not in s,'files_header_open_folder_icon':'self.files_output_folder_button' in s and 'R42EK: open the latest converter output folder from the FILES header' in s,'file_converter_clear_label_short':'text=\"Clear\"' in s and 'text=\"Clear converter\"' not in s,'take_all_by_file_type':'text=\"Take all:\"' in s and 'def _file_converter_take_all_from_files' in s,'drop_box_contains_held_list':'self.file_converter_queue_textbox = ctk.CTkTextbox(\n            self.file_converter_drop_frame' in s,'drag_files_rows_to_converter':'def _session_file_drop_target_is_converter' in s and 'source_label=\"FILES drag\"' in s,'image_window_downloads_then_converts':'source_label=\"image-window conversion\"' in s and 'outputs will enter FILES after conversion' in s,'video_window_downloads_then_converts':'source_label=\"video-audio-window conversion\"' in s and 'convert_target_format' in s,'media_window_keep_original_control':'id=\"convertKeep\"' in s and 'keep_original' in s,'media_window_target_format_control':'id=\"convertTarget\"' in s and 'target_format' in s,'no_convert_to_converter_status':'Sent ${{payload.queued}} media candidate(s) to File Converter' not in s and 'Sent ${{payload.queued}} image(s) to File Converter' not in s,'r42ek_marker':'R42EK_FILE_CONVERTER_WINDOW_AND_FILES_CLEANUP' in s}; print(json.dumps(checks, indent=2)); raise SystemExit(0 if all(checks.values()) else 1)" || exit /b 1
echo [DONE] R42EK smoke passed.
