@echo off
setlocal
cd /d "%~dp0..\.."
echo [R42DN] Building normal-access-first universal layer reference ZIP...
for /f %%i in ('powershell -NoProfile -Command "Get-Date -Format yyyyMMdd_HHmmss"') do set STAMP=%%i
set "OUTROOT=profile_media_live_captures\r42dn_normal_access_first_universal_layer"
set "OUT=%OUTROOT%\probe_%STAMP%"
call "%~dp0_r42dn_python.cmd" profile_media_normal_access_layer_r42dn.py --probe --output-dir "%OUT%"
if errorlevel 1 exit /b %ERRORLEVEL%
powershell -NoProfile -ExecutionPolicy Bypass -Command "$ErrorActionPreference='Stop'; Add-Type -AssemblyName System.IO.Compression.FileSystem; $root=(Get-Location).Path; $stamp='%STAMP%'; $stage=Join-Path $env:TEMP ('r42dn_ref_' + $stamp); if(Test-Path -LiteralPath $stage){Remove-Item -LiteralPath $stage -Recurse -Force}; New-Item -ItemType Directory -Force -Path $stage | Out-Null; $files=@('main.py','profile_media_normal_access_layer_r42dn.py','profile_media_normal_access_layer_r42dn_test.py','profile_media_universal_source_link_adapter_r42dk.py','profile_media_universal_source_link_adapter_r42dl.py','profile_media_access_escalation_policy_r42dm.py','source_adapters.py','source_resource_state.py','R42DN_NORMAL_ACCESS_FIRST_UNIVERSAL_LAYER_NOTES_20260906.md','tools\webview2_source_role_editor_native\smoke_r42dn_normal_access_first_universal_layer.cmd','tools\webview2_source_role_editor_native\probe_r42dn_normal_access_first_universal_layer.cmd','tools\webview2_source_role_editor_native\decide_r42dn_normal_access_route.cmd','tools\webview2_source_role_editor_native\build_r42dn_normal_access_first_universal_layer_zip.cmd','tools\webview2_source_role_editor_native\make_r42dn_active_worker_source_upload_zip.cmd','tools\webview2_source_role_editor_native\_r42dn_python.cmd'); foreach($rel in $files){ $src=Join-Path $root $rel; if(Test-Path -LiteralPath $src){ $dst=Join-Path $stage ('project\' + $rel); New-Item -ItemType Directory -Force -Path (Split-Path -Parent $dst) | Out-Null; Copy-Item -LiteralPath $src -Destination $dst -Force } }; $probe=Join-Path $root '%OUT%'; if(Test-Path -LiteralPath $probe){ Copy-Item -LiteralPath $probe -Destination (Join-Path $stage '_r42dn_probe_outputs') -Recurse -Force }; $zip=Join-Path $root ('%OUTROOT%\r42dn_normal_access_first_universal_layer_' + $stamp + '.zip'); if(Test-Path -LiteralPath $zip){Remove-Item -LiteralPath $zip -Force}; [System.IO.Compression.ZipFile]::CreateFromDirectory($stage,$zip); $dl=Join-Path $env:USERPROFILE ('Downloads\' + (Split-Path -Leaf $zip)); Copy-Item -LiteralPath $zip -Destination $dl -Force; Write-Host '[DONE] Created ZIP:' $zip; Write-Host '[DONE] Copied ZIP to Downloads:' $dl"
