@echo off
setlocal
cd /d "%~dp0..\.."
echo [R42DK] Building universal source/link adapter reference ZIP...
call tools\webview2_source_role_editor_native\probe_r42dk_universal_source_link_adapter.cmd
set "STAMP=%DATE:/=%_%TIME::=%"
set "STAMP=%STAMP: =0%"
set "OUTDIR=profile_media_live_captures\r42dk_universal_source_link_adapter"
set "ZIP=%OUTDIR%\r42dk_universal_source_link_adapter_%STAMP%.zip"
powershell -NoProfile -ExecutionPolicy Bypass -Command "$ErrorActionPreference='Stop'; $root=(Get-Location).Path; $out=Join-Path $root '%OUTDIR%'; New-Item -ItemType Directory -Force -Path $out | Out-Null; $stage=Join-Path $env:TEMP ('r42dk_ref_' + [guid]::NewGuid().ToString('N')); New-Item -ItemType Directory -Force -Path $stage | Out-Null; $files=@('profile_media_universal_source_link_adapter_r42dk.py','profile_media_universal_source_link_adapter_r42dk_test.py','source_adapters.py','source_adapters_test.py','source_resource_state.py','source_resource_state_test.py','R42DK_UNIVERSAL_SOURCE_LINK_ADAPTER_NOTES_20260906.md','tools\webview2_source_role_editor_native\_r42dk_python.cmd','tools\webview2_source_role_editor_native\smoke_r42dk_universal_source_link_adapter.cmd','tools\webview2_source_role_editor_native\probe_r42dk_universal_source_link_adapter.cmd','tools\webview2_source_role_editor_native\decide_r42dk_universal_source_link_route.cmd','tools\webview2_source_role_editor_native\build_r42dk_universal_source_link_adapter_zip.cmd'); foreach($rel in $files){ $src=Join-Path $root $rel; if(Test-Path -LiteralPath $src){ $dst=Join-Path $stage $rel; New-Item -ItemType Directory -Force -Path (Split-Path -Parent $dst) | Out-Null; Copy-Item -LiteralPath $src -Destination $dst -Force } }; if(Test-Path -LiteralPath (Join-Path $root 'profile_media_live_captures\r42dk_universal_source_link_adapter')){ Copy-Item -LiteralPath (Join-Path $root 'profile_media_live_captures\r42dk_universal_source_link_adapter') -Destination (Join-Path $stage '_r42dk_receipts') -Recurse -Force -ErrorAction SilentlyContinue }; $zip=Join-Path $out ('r42dk_universal_source_link_adapter_' + (Get-Date -Format 'yyyyMMdd_HHmmss') + '.zip'); if(Test-Path -LiteralPath $zip){ Remove-Item -LiteralPath $zip -Force }; Compress-Archive -Path (Join-Path $stage '*') -DestinationPath $zip -Force; $dl=Join-Path $env:USERPROFILE ('Downloads\' + (Split-Path -Leaf $zip)); Copy-Item -LiteralPath $zip -Destination $dl -Force; Write-Host '[DONE] Created ZIP:' $zip; Write-Host '[DONE] Copied ZIP to Downloads:' $dl"
