@echo off
setlocal
cd /d "%~dp0..\.."
echo [R42DO] Building universal worker source-router reference ZIP...
for /f %%i in ('powershell -NoProfile -Command "Get-Date -Format yyyyMMdd_HHmmss"') do set STAMP=%%i
set "OUTROOT=profile_media_live_captures\r42do_universal_worker_source_router"
set "OUT=%OUTROOT%\probe_%STAMP%"
call "%~dp0_r42do_python.cmd" profile_media_universal_worker_source_router_r42do.py --probe --output-dir "%OUT%"
if errorlevel 1 exit /b %ERRORLEVEL%
powershell -NoProfile -ExecutionPolicy Bypass -Command "$ErrorActionPreference='Stop'; Add-Type -AssemblyName System.IO.Compression.FileSystem; $root=(Get-Location).Path; $stamp='%STAMP%'; $stage=Join-Path $env:TEMP ('r42do_ref_' + $stamp); if(Test-Path -LiteralPath $stage){Remove-Item -LiteralPath $stage -Recurse -Force}; New-Item -ItemType Directory -Force -Path $stage | Out-Null; $files=@('main.py','profile_media_universal_worker_source_router_r42do.py','profile_media_universal_worker_source_router_r42do_test.py','profile_media_normal_access_layer_r42dn.py','profile_media_access_escalation_policy_r42dm.py','profile_media_universal_source_link_adapter_r42dk.py','profile_media_universal_source_link_adapter_r42dl.py','source_adapters.py','source_resource_state.py','R42DO_UNIVERSAL_WORKER_SOURCE_ROUTER_NOTES_20260906.md','tools\webview2_source_role_editor_native\_r42do_python.cmd','tools\webview2_source_role_editor_native\smoke_r42do_universal_worker_source_router.cmd','tools\webview2_source_role_editor_native\probe_r42do_universal_worker_source_router.cmd','tools\webview2_source_role_editor_native\decide_r42do_worker_source_route.cmd','tools\webview2_source_role_editor_native\build_r42do_universal_worker_source_router_zip.cmd','tools\webview2_source_role_editor_native\make_r42do_active_worker_source_upload_zip.cmd'); foreach($rel in $files){ $src=Join-Path $root $rel; if(Test-Path -LiteralPath $src){ $dst=Join-Path $stage ('project\' + $rel); New-Item -ItemType Directory -Force -Path (Split-Path -Parent $dst) | Out-Null; Copy-Item -LiteralPath $src -Destination $dst -Force } }; $probe=Join-Path $root '%OUT%'; if(Test-Path -LiteralPath $probe){ Copy-Item -LiteralPath $probe -Destination (Join-Path $stage '_r42do_probe_outputs') -Recurse -Force }; $zip=Join-Path $root ('%OUTROOT%\r42do_universal_worker_source_router_' + $stamp + '.zip'); if(Test-Path -LiteralPath $zip){Remove-Item -LiteralPath $zip -Force}; [System.IO.Compression.ZipFile]::CreateFromDirectory($stage,$zip); $dl=Join-Path $env:USERPROFILE ('Downloads\' + (Split-Path -Leaf $zip)); Copy-Item -LiteralPath $zip -Destination $dl -Force; Write-Host '[DONE] Created ZIP:' $zip; Write-Host '[DONE] Copied ZIP to Downloads:' $dl"
