@echo off
setlocal
cd /d "%~dp0..\.."
echo [R42DR] Building normal-access feature receipt reference ZIP...
call tools\webview2_source_role_editor_native\probe_r42dr_normal_access_feature_receipts.cmd
if errorlevel 1 exit /b 1
call tools\webview2_source_role_editor_native\_r42dr_python.cmd -c "import os, zipfile, shutil, pathlib, datetime; root=pathlib.Path.cwd(); stamp=datetime.datetime.now().strftime('%Y%m%d_%H%M%S'); out=root/'profile_media_live_captures'/'r42dr_normal_access_feature_receipts'; out.mkdir(parents=True, exist_ok=True); zip_path=out/('r42dr_normal_access_feature_receipts_'+stamp+'.zip'); files=['main.py','source_adapters.py','source_resource_state.py','profile_media_normal_access_feature_receipts_r42dr.py','profile_media_normal_access_feature_receipts_r42dr_test.py','profile_media_normal_access_provider_layer_r42dq.py','profile_media_account_channel_worker_adapter_r42dp.py','profile_media_universal_worker_source_router_r42do.py','profile_media_normal_access_layer_r42dn.py','profile_media_access_escalation_policy_r42dm.py','R42DR_NORMAL_ACCESS_FEATURE_RECEIPTS_NOTES_20260907.md','tools/webview2_source_role_editor_native/_r42dr_python.cmd','tools/webview2_source_role_editor_native/smoke_r42dr_normal_access_feature_receipts.cmd','tools/webview2_source_role_editor_native/probe_r42dr_normal_access_feature_receipts.cmd','tools/webview2_source_role_editor_native/decide_r42dr_normal_access_feature_receipt.cmd','tools/webview2_source_role_editor_native/build_r42dr_normal_access_feature_receipts_zip.cmd','tools/webview2_source_role_editor_native/make_r42dr_active_normal_access_worker_upload_zip.cmd']; probes=list((root/'profile_media_live_captures'/'r42dr_normal_access_feature_receipts').glob('probe_*')); latest=max([p for p in probes if p.is_dir()], key=lambda p:p.stat().st_mtime, default=None); z=zipfile.ZipFile(zip_path,'w',zipfile.ZIP_DEFLATED); [z.write(root/f, 'project/'+f.replace('\\\\','/')) for f in files if (root/f).is_file()]; [z.write(p, '_r42dr_probe_outputs/'+str(p.relative_to(latest)).replace('\\\\','/')) for p in latest.rglob('*') if latest and p.is_file()]; z.close(); dl=pathlib.Path(os.environ.get('USERPROFILE',''))/'Downloads'/zip_path.name; shutil.copy2(zip_path, dl); print('[DONE] Created ZIP:', zip_path); print('[DONE] Copied ZIP to Downloads:', dl)"
if errorlevel 1 exit /b 1
exit /b 0
